name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - dev-release  # Trigger deployment on push to the dev-release branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    permissions:
      contents: write  # Allow write access to the repository

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set the Node.js version

    - name: Install Dependencies
      run: npm install  # Install dependencies

    - name: Build Project
      run: npm run build  # Build the Next.js project, which includes the static export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # The static files will be in the `out` directory
