name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - dev-release

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to the repository

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Export Project to Static Files
    run: npm run export  # Export the Next.js app to static files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # Deploy the static files from the `out` folder
